# Generated by Django 2.2.12 on 2023-01-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookupcode', models.CharField(max_length=30, verbose_name='lookupcode')),
                ('lookname', models.CharField(max_length=30, verbose_name='lookname')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'lookup',
                'db_table': 'lookup',
            },
        ),
        migrations.CreateModel(
            name='lookupdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookupdetdesc', models.CharField(max_length=200)),
                ('lookupvalue', models.CharField(max_length=100)),
                ('lookuplevel', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('user_status', models.CharField(choices=[('Other', 'Other'), ('Developer', 'Developer'), ('Tester', 'Tester')], default='Other', max_length=10)),
                ('lookup_other_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lookup other value')),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.lookup')),
            ],
            options={
                'verbose_name_plural': 'lookupdet',
                'db_table': 'lookupdet',
            },
        ),
    ]
